name: Deploy React App to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Create Deployment Package
        # Zip everything AWS needs: Dockerfile + source code
        # Dockerfile MUST be at the root of the zip for Docker platform to work
        run: zip -r notification.zip . -x "**.git**" "node_modules/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: messaging-frontend
          environment_name: messaging-frontend-prod
          version_label: app-${{ github.sha }}
          region: us-east-1
          deployment_package: notification.zip

      - name: Deployed!
        run: echo App deployed to ELB